version: '2'

services:
  execution-web:
    image: maven:3-jdk-8
    container_name: execution-web
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - "8080:8080"
    links:
      - execution-db
     #command:
      # - mvn clean verify org.codehaus.cargo:cargo-maven2-plugin:run
  execution-db:
    image: "microsoft/mssql-server-linux"
    environment:
      - SA_PASSWORD=Long_Secret
      - ACCEPT_EULA=Y
    ports:
      - "1432:1433"

