FROM anapsix/alpine-java
COPY ./target/Executions-1.0-SNAPSHOT.jar /home/Executions-1.0-SNAPSHOT.jar
CMD ["java","-jar","/home/Executions-1.0-SNAPSHOT.jar"]

# FROM microsoft/mssql-server-linux
# COPY ./target/Executions-1.0-SNAPSHOT.jar .

# # CMD java -jar target/Executions-1.0-SNAPSHOT.jar
