version: '2'

services:
  web:
    image: maven:3-jdk-8
    container_name: web
    ports:
     - "8080:8080"
  execution-db:
    image: "microsoft/mssql-server-linux"
    environment:
      - SA_PASSWORD=Long_Secret
      - ACCEPT_EULA=Y
