version: '2'

services:
  execution-web:
    image: maven:3-jdk-8
    container_name: execution-web
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - "8080:8080"
    links:
      - execution-db
    # command:
      # - java -jar Executions-1.0-SNAPSHOT.jar
  execution-db:
    image: "microsoft/mssql-server-linux"
    environment:
      - SA_PASSWORD=Long_Secret
      - ACCEPT_EULA=Y

